# Generated by Django 4.0.4 on 2022-05-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_categoria_delete_conta_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.CharField(default='/static/media/avatardefault.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.CharField(default='/static/media/avatardefault.png', max_length=100),
        ),
    ]
