# Generated by Django 4.0.4 on 2022-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_cliente_foto_alter_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.CharField(default='/static/media/computer.png', max_length=100),
        ),
    ]
