# Generated by Django 4.0.3 on 2022-05-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='foto',
        ),
    ]
