# Generated by Django 4.0.3 on 2022-05-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_produto_foto_produtoimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoImages',
        ),
    ]
