# Generated by Django 4.0.3 on 2022-05-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_produto_foto_rating'),
        ('loja', '0011_rating'),
    ]

    operations = [
    ]
