# Generated by Django 4.0.3 on 2022-05-15 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 19, 36, 16, 2200)),
        ),
    ]
